### ISSUE TITLE
Dollar sign appended at end of NMDC TTH search requests

### ISSUE THREAD

**Issue by aler9** [direct-connect/go-dc#22]
A failure in automated tests made me notice that the library explicitly appends a dollar sign at the end of every TTH search request:

https://github.com/direct-connect/go-dc/blob/9b3b849481748ab725415599f18bd6edcd351877/nmdc/search.go#L92

In this way, requests become:
> $Search 192.168.1.5:412 F?T?0?9?TTH:TO32WPD6AQE7VA7654HEAM5GKFQGIL7F2BEKFNA$|

instead of:
> $Search 192.168.1.5:412 F?T?0?9?TTH:TO32WPD6AQE7VA7654HEAM5GKFQGIL7F2BEKFNA|

what's the reason of this behavior? i could not find an explanation in both specifications and existing clients:
http://nmdc.sourceforge.net/Versions/NMDC-1.3.html#_search

thanks

**Comment by dennwc** [comment]
Sometimes clients send the trailing `$`, I've seen this in the wild.

However you are right. On further examination of the source code, I see that most popular clients don't send trailing `$`. Marking this as a bug.
